[build-system]
[project]
name = "hashly"
version = "1.0"
description = "A simple Hash CLI tool"
readme = "README.md"
authors = [
    {name = "Katia Ventouri", email = "kat.vent@proton.me"}
]
requires-python = ">=3.13"
dependencies = "typer>=0.15.4"
